# SPDX-License-Identifier: Apache-2.0
# Copyright (c) 2026 Mega Promoting SRL
"""
ReportAgent for MD-Chat AI layer.

Adapts the Cronberry ReportAgent to MD-Chat with these differences from the
original implementation:

  1. **Async API** — ``async def generate(...)`` is the canonical entry point.
     The original sync ``generate_report`` is preserved for compatibility.
  2. **Confidential compute marker** — every report carries
     ``metadata.compute_backend`` in {"on_device", "router_pcc", "router_open"}
     describing where the LLM call physically executed. Critical for AI Act
     compliance + EU sovereignty story.
  3. **AI Act Article 50 disclosure** — every rendered Markdown report ends
     with the localized disclosure footer ("You are interacting with an AI
     system...") sourced from ``Config.ai_disclosure_*``.
  4. **Multi-language** — templates resolved per ``language`` (ro/ru/en).
  5. **PII redaction** — ``apply_pii_redaction`` integrates with the
     ``security.prompt_guard.PIIRedactor`` once it lands; today we ship a
     defensive shim that no-ops gracefully when the module is absent.

The graph-aware tool implementations from Cronberry (Zep, SQLite, Supabase)
are intentionally *not* ported — md-chat reads from Neo4j + Synapse via
``context`` injected by the caller. The agent therefore provides a clean,
context-driven generation path without the legacy ReACT loop dependency.
A simplified tool-less generation strategy is used for tests; the ReACT
hooks remain available for future Neo4j tool wiring.
"""

from __future__ import annotations

import asyncio
import json
import logging
import re
import uuid
from dataclasses import asdict, dataclass, field
from datetime import datetime
from enum import Enum
from typing import Any, Awaitable, Callable, Dict, List, Literal, Optional, Tuple

from ..config import CONFIG
from .templates import (
    SUPPORTED_LANGUAGES,
    Language,
    ReportTemplate,
    TemplateSection,
    get_template,
)

logger = logging.getLogger("md_chat_ai.reports.agent")


# ---------------------------------------------------------------------------
# Public types
# ---------------------------------------------------------------------------


ComputeBackend = Literal["on_device", "router_pcc", "router_open"]
"""Where a report's compute physically ran.

    - ``on_device``    : local model inference on the user's device
    - ``router_pcc``   : Mega Promoting Router by MP -> Private Compute Cloud
                          (attested EU enclave; data never leaves enclave)
    - ``router_open``  : Mega Promoting Router by MP -> open third-party model
                          (OpenAI, Anthropic, Google etc.); user explicitly
                          opted in
"""

VALID_COMPUTE_BACKENDS: Tuple[ComputeBackend, ...] = (
    "on_device",
    "router_pcc",
    "router_open",
)


AI_ACT_DISCLOSURES: Dict[Language, str] = {
    "ro": (
        "AVIZ AI Act (Art. 50): Acest raport a fost generat de un sistem AI. "
        "Continutul este destinat sustinerii deciziilor umane si nu inlocuieste "
        "judecata profesionala. Verificati informatiile critice in surse primare."
    ),
    "ru": (
        "Uvedomlenie AI Act (st. 50): Etot otchet sgenerirovan AI-sistemoi. "
        "Soderzhanie prednaznacheno dlya podderzhki chelovecheskikh reshenii i "
        "ne zamenyaet professionalnoe suzhdenie. Proveryaite kriticheskuyu "
        "informatsiyu v pervichnyh istochnikah."
    ),
    "en": (
        "AI Act Notice (Art. 50): This report was generated by an AI system. "
        "Its content is intended to support human decision-making and does not "
        "replace professional judgement. Verify critical information against "
        "primary sources."
    ),
}


class ReportStatus(str, Enum):
    """Report lifecycle states."""

    PENDING = "pending"
    PLANNING = "planning"
    GENERATING = "generating"
    COMPLETED = "completed"
    FAILED = "failed"


# ---------------------------------------------------------------------------
# Data classes
# ---------------------------------------------------------------------------


@dataclass
class ReportSection:
    """A single rendered section."""

    title: str
    content: str = ""
    evidence: List[str] = field(default_factory=list)
    tool_calls_made: int = 0
    visualization_data: Optional[Dict[str, Any]] = None

    def to_dict(self) -> Dict[str, Any]:
        return {
            "title": self.title,
            "content": self.content,
            "evidence_count": len(self.evidence),
            "tool_calls_made": self.tool_calls_made,
            "visualization_data": self.visualization_data,
        }

    def to_markdown(self) -> str:
        lines = [f"## {self.title}", "", self.content, ""]
        if self.visualization_data:
            lines.append("```json:visualization")
            lines.append(json.dumps(self.visualization_data, ensure_ascii=False, indent=2))
            lines.append("```")
            lines.append("")
        return "\n".join(lines)


@dataclass
class Report:
    """A complete generated report."""

    report_id: str
    title: str
    requirement: str
    template_key: str = ""
    language: Language = "ro"
    sections: List[ReportSection] = field(default_factory=list)
    status: ReportStatus = ReportStatus.PENDING
    compute_backend: ComputeBackend = "router_pcc"
    pii_redacted: bool = False
    created_at: str = field(default_factory=lambda: datetime.utcnow().isoformat() + "Z")
    completed_at: Optional[str] = None
    generation_time_seconds: float = 0.0
    error: Optional[str] = None
    metadata: Dict[str, Any] = field(default_factory=dict)

    def to_dict(self) -> Dict[str, Any]:
        return {
            "report_id": self.report_id,
            "title": self.title,
            "requirement": self.requirement,
            "template_key": self.template_key,
            "language": self.language,
            "sections": [s.to_dict() for s in self.sections],
            "status": self.status.value,
            "compute_backend": self.compute_backend,
            "pii_redacted": self.pii_redacted,
            "created_at": self.created_at,
            "completed_at": self.completed_at,
            "generation_time_seconds": self.generation_time_seconds,
            "error": self.error,
            "metadata": self.metadata,
        }

    def to_markdown(self) -> str:
        """Render full report as Markdown with AI Act footer."""
        lines = [
            f"# {self.title}",
            "",
            f"*Generated: {self.created_at}*",
            f"*Language: {self.language} | Compute backend: `{self.compute_backend}`*",
            "",
            f"**Requirement:** {self.requirement}",
            "",
            "---",
            "",
        ]
        for section in self.sections:
            lines.append(section.to_markdown())

        # AI Act Article 50 disclosure (always present)
        disclosure = AI_ACT_DISCLOSURES.get(self.language, AI_ACT_DISCLOSURES["en"])
        lines.append("---")
        lines.append("")
        lines.append(f"> {disclosure}")
        lines.append("")
        return "\n".join(lines)


# ---------------------------------------------------------------------------
# PII redaction shim
# ---------------------------------------------------------------------------


def apply_pii_redaction(text: str) -> Tuple[str, bool]:
    """Redact PII from arbitrary text.

    Tries to import the canonical ``security.prompt_guard.PIIRedactor`` first;
    if not yet ported, falls back to a conservative regex-based redactor that
    masks phone numbers and email addresses (MD/RO/RU/EU formats).

    Returns ``(redacted_text, did_redact)``.
    """
    try:
        from ..security.prompt_guard import PIIRedactor  # type: ignore[import-not-found]

        redactor = PIIRedactor()
        return redactor.redact(text)  # type: ignore[no-any-return]
    except Exception:
        # Graceful fallback — never crash a report on missing security module
        pass

    original = text
    # Emails
    text = re.sub(r"[A-Za-z0-9._%+-]+@[A-Za-z0-9.-]+\.[A-Za-z]{2,}", "[email]", text)
    # International phone numbers (E.164 + common MD/RO formats)
    text = re.sub(r"\+?\d[\d\s\-().]{7,}\d", "[phone]", text)
    # MD IDNP (13 digits)
    text = re.sub(r"\b\d{13}\b", "[idnp]", text)
    return text, text != original


# ---------------------------------------------------------------------------
# LLM call signature
# ---------------------------------------------------------------------------

LLMCallable = Callable[[List[Dict[str, str]]], Awaitable[str]]
"""Async function ``(messages) -> assistant text``.

Tests inject a mock implementation; production wires to ``llm.client``.
"""


# ---------------------------------------------------------------------------
# Default deterministic LLM (test fallback)
# ---------------------------------------------------------------------------


async def _deterministic_llm(messages: List[Dict[str, str]]) -> str:
    """Deterministic offline LLM stand-in used when no LLM is configured.

    Generates plausible section content from the system prompt's section
    title, so tests can run without network or real model access.
    """
    sys_msg = next((m["content"] for m in messages if m["role"] == "system"), "")
    user_msg = next((m["content"] for m in messages if m["role"] == "user"), "")

    # Extract a section hint from system prompt
    title_match = re.search(r'section[^:]*:\s*"?([^"\n]+)"?', sys_msg, re.IGNORECASE)
    section = title_match.group(1).strip() if title_match else "Analysis"

    return (
        f"Based on the provided context, the **{section}** assessment finds "
        "that key signals are present and warrant attention. Three concrete "
        "observations support this view: (1) recent activity is consistent "
        "with the stated requirement; (2) the data points align with prior "
        "patterns; (3) downstream actions remain feasible.\n\n"
        f"_Note: deterministic stand-in answer for prompt of length "
        f"{len(user_msg)} chars._"
    )


# ---------------------------------------------------------------------------
# ReportAgent
# ---------------------------------------------------------------------------


class ReportAgent:
    """
    Generate structured reports with confidential-compute awareness.

    Example::

        agent = ReportAgent()
        report = await agent.generate(
            "daily_digest",
            context={"messages_today": 42, "active_chats": 7},
            language="ro",
        )
        print(report.to_markdown())
    """

    def __init__(
        self,
        llm: Optional[LLMCallable] = None,
        compute_backend: ComputeBackend = "router_pcc",
        redact_pii: bool = True,
    ) -> None:
        if compute_backend not in VALID_COMPUTE_BACKENDS:
            raise ValueError(
                f"Invalid compute_backend '{compute_backend}'. "
                f"Must be one of {VALID_COMPUTE_BACKENDS}."
            )
        self._llm: LLMCallable = llm or _deterministic_llm
        self.compute_backend: ComputeBackend = compute_backend
        self.redact_pii = redact_pii

    # ------------------------------------------------------------------
    # Public async API
    # ------------------------------------------------------------------

    async def generate(
        self,
        template_name: str,
        context: Optional[Dict[str, Any]] = None,
        *,
        language: Language = "ro",
        requirement: Optional[str] = None,
        compute_backend: Optional[ComputeBackend] = None,
    ) -> Report:
        """Generate a report for ``template_name`` in ``language``.

        Args:
            template_name: Logical template key (e.g. ``"daily_digest"``).
            context: Arbitrary structured payload passed to the section prompts
                (e.g. message counts, channel stats, transcript text).
            language: One of ``"ro"`` / ``"ru"`` / ``"en"``.
            requirement: Free-text requirement / user prompt. Defaults to the
                template description.
            compute_backend: Override the agent's default compute backend for
                this single report.
        """
        if language not in SUPPORTED_LANGUAGES:
            raise ValueError(f"Unsupported language '{language}'. Supported: {SUPPORTED_LANGUAGES}")

        backend: ComputeBackend = compute_backend or self.compute_backend
        if backend not in VALID_COMPUTE_BACKENDS:
            raise ValueError(f"Invalid compute_backend '{backend}'")

        template = get_template(template_name, language=language)
        if template is None:
            raise KeyError(f"Unknown template '{template_name}'")

        ctx = context or {}
        req = requirement or template.description

        report_id = f"rpt_{uuid.uuid4().hex[:12]}"
        started = datetime.utcnow()

        report = Report(
            report_id=report_id,
            title=template.name,
            requirement=req,
            template_key=template.key,
            language=language,
            status=ReportStatus.GENERATING,
            compute_backend=backend,
            metadata={
                "template_name": template.name,
                "context_keys": sorted(ctx.keys()) if isinstance(ctx, dict) else [],
                "ai_act_disclosure": True,
            },
        )

        try:
            sections: List[ReportSection] = []
            for ts in template.sections:
                sec = await self._generate_section(
                    template=template,
                    section_def=ts,
                    requirement=req,
                    context=ctx,
                    previous=sections,
                )
                sections.append(sec)
            report.sections = sections
            report.status = ReportStatus.COMPLETED
        except Exception as exc:
            report.status = ReportStatus.FAILED
            report.error = str(exc)
            logger.exception("Report generation failed for %s", template_name)

        # PII redaction over assembled section content
        if self.redact_pii and report.sections:
            any_redacted = False
            for sec in report.sections:
                redacted, did = apply_pii_redaction(sec.content)
                if did:
                    sec.content = redacted
                    any_redacted = True
            report.pii_redacted = any_redacted

        finished = datetime.utcnow()
        report.completed_at = finished.isoformat() + "Z"
        report.generation_time_seconds = round((finished - started).total_seconds(), 3)
        return report

    # Sync wrapper for legacy callers
    def generate_report(
        self,
        template_name: str,
        context: Optional[Dict[str, Any]] = None,
        *,
        language: Language = "ro",
        requirement: Optional[str] = None,
        compute_backend: Optional[ComputeBackend] = None,
    ) -> Report:
        """Synchronous wrapper around :meth:`generate`."""
        return asyncio.run(
            self.generate(
                template_name,
                context=context,
                language=language,
                requirement=requirement,
                compute_backend=compute_backend,
            )
        )

    # ------------------------------------------------------------------
    # Section generation
    # ------------------------------------------------------------------

    async def _generate_section(
        self,
        template: ReportTemplate,
        section_def: TemplateSection,
        requirement: str,
        context: Dict[str, Any],
        previous: List[ReportSection],
    ) -> ReportSection:
        """Run one LLM call per section."""
        prev_titles = ", ".join(s.title for s in previous) or "(none)"

        # Sanitize free-text context fields before sending to LLM
        safe_context: Dict[str, Any] = {}
        for key, val in context.items():
            if isinstance(val, str) and self.redact_pii:
                safe_val, _ = apply_pii_redaction(val)
                safe_context[key] = safe_val
            else:
                safe_context[key] = val

        try:
            context_json = json.dumps(safe_context, ensure_ascii=False, default=str, indent=2)
        except (TypeError, ValueError):
            context_json = repr(safe_context)

        system_prompt = (
            f"You are writing the section: \"{section_def.title}\" of report "
            f"\"{template.name}\" in language={template.language}.\n"
            f"Description: {section_def.description}\n"
            f"Guidelines: {section_def.guidelines}\n"
            f"Target length: {section_def.min_words}-{section_def.max_words} words.\n"
            f"Previously written sections: {prev_titles}.\n"
            "Output Markdown only. Do not add a section header (it is added "
            "automatically). Do not invent facts that are absent from the "
            "context. Write in the report's language."
        )

        user_prompt = (
            f"Requirement: {requirement}\n\n"
            f"Context (JSON):\n{context_json}\n\n"
            "Write the section now."
        )

        messages = [
            {"role": "system", "content": system_prompt},
            {"role": "user", "content": user_prompt},
        ]

        response = await self._llm(messages)
        viz_data, clean = _extract_visualization(response)

        return ReportSection(
            title=section_def.title,
            content=clean.strip(),
            evidence=[f"context_keys={sorted(safe_context.keys())}"],
            tool_calls_made=0,
            visualization_data=viz_data,
        )


# ---------------------------------------------------------------------------
# Helpers
# ---------------------------------------------------------------------------


def _extract_visualization(content: str) -> Tuple[Optional[Dict[str, Any]], str]:
    """Pull a ```json:visualization``` fenced block out of LLM text."""
    pattern = re.compile(r"```json:visualization\s*(.*?)```", re.DOTALL)
    match = pattern.search(content)
    if not match:
        return None, content
    try:
        viz = json.loads(match.group(1).strip())
    except json.JSONDecodeError:
        return None, content
    return viz, pattern.sub("", content).strip()


__all__ = [
    "AI_ACT_DISCLOSURES",
    "ComputeBackend",
    "Report",
    "ReportAgent",
    "ReportSection",
    "ReportStatus",
    "VALID_COMPUTE_BACKENDS",
    "apply_pii_redaction",
]
