# Copyright 2026 Mega Promoting SRL
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Derived from Cronberry (Mega Promoting SRL).
"""
Message Optimizer — tests message variants on a self-twin before real send.

Used by:
- Any AI agent that needs the human owner to draft outgoing messages
- The human user who wants to optimise a message before sending
- Compose-time A/B testing in the MD-Chat client

Flow:
1. Caller provides a draft message + objective
2. Optimizer generates N variants (different tones/approaches)
3. Each variant is tested against the user's own self-twin
4. Twin's predicted reception is analysed
5. Best variant returned with confidence score
6. Caller sends the winning message manually

Also supports:
- A/B test mode: head-to-head test of two specific messages
- Batch mode: optimize messages for multiple recipients at once
- Learning mode: record which optimized messages actually worked
"""

from __future__ import annotations

import logging
import time
from dataclasses import dataclass, field
from datetime import datetime
from typing import Any

from ..llm.client import LLMClient
from .digital_twin import DigitalTwin, SelfProfile, TwinResponse

logger = logging.getLogger("md_chat_ai.agents.message_optimizer")


# ======================================================================
# Data classes
# ======================================================================


@dataclass
class MessageVariant:
    """A single message variant generated by the optimizer."""

    text: str
    tone: str
    approach: str
    rationale: str  # Why this variant was generated


@dataclass
class VariantTestResult:
    """Result from testing one variant on the self-twin."""

    variant: MessageVariant
    twin_response: str
    success_score: float  # 0-1
    naturalness_score: float  # 0-1 (how natural does the message sound)
    risk_score: float  # 0-1 (higher = more risky)
    predicted_outcome: str  # "will_respond_positively", "will_ignore", "will_respond_negatively"
    reasoning: str  # Why this score

    def to_dict(self) -> dict[str, Any]:
        return {
            "variant": {
                "text": self.variant.text,
                "tone": self.variant.tone,
                "approach": self.variant.approach,
                "rationale": self.variant.rationale,
            },
            "twin_response": self.twin_response,
            "success_score": self.success_score,
            "naturalness_score": self.naturalness_score,
            "risk_score": self.risk_score,
            "predicted_outcome": self.predicted_outcome,
            "reasoning": self.reasoning,
        }


@dataclass
class OptimizationResult:
    """Full result from an optimization run."""

    user_id: str
    user_name: str
    objective: str
    original_message: str | None

    variants_tested: list[VariantTestResult]

    winner: VariantTestResult | None = None
    runner_up: VariantTestResult | None = None
    do_not_send: list[VariantTestResult] = field(default_factory=list)

    confidence: float = 0.0
    estimated_success_rate: float = 0.0
    warnings: list[str] = field(default_factory=list)

    def to_dict(self) -> dict[str, Any]:
        return {
            "user_id": self.user_id,
            "user_name": self.user_name,
            "objective": self.objective,
            "original_message": self.original_message,
            "variants_tested": [v.to_dict() for v in self.variants_tested],
            "winner": self.winner.to_dict() if self.winner else None,
            "runner_up": self.runner_up.to_dict() if self.runner_up else None,
            "do_not_send": [v.to_dict() for v in self.do_not_send],
            "confidence": self.confidence,
            "estimated_success_rate": self.estimated_success_rate,
            "warnings": self.warnings,
        }


# ======================================================================
# Message Optimizer
# ======================================================================


class MessageOptimizer:
    """Optimize messages before sending — backed by the user's self-twin."""

    def __init__(self, llm_client: LLMClient | None = None) -> None:
        self._llm = llm_client
        self._history: list[dict[str, Any]] = []

    @property
    def llm(self) -> LLMClient:
        """Lazily initialise the LLM client."""
        if self._llm is None:
            self._llm = LLMClient()
        return self._llm

    # ------------------------------------------------------------------
    # Public: optimize
    # ------------------------------------------------------------------

    def optimize(
        self,
        self_profile: SelfProfile,
        objective: str,
        draft_message: str | None = None,
        num_variants: int = 5,
        constraints: list[str] | None = None,
    ) -> OptimizationResult:
        """
        Optimize a message for a specific user using their self-twin.

        If draft_message provided: generates variants of that message.
        If no draft: generates variants from scratch based on objective.

        Each variant is tested on the user's self-twin.
        """
        t0 = time.monotonic()

        twin = DigitalTwin(self_profile)

        logger.info(
            "Optimizing message for %s: objective=%s, variants=%d",
            self_profile.name,
            objective[:80],
            num_variants,
        )

        variants = self._generate_variants(self_profile, objective, draft_message, num_variants, constraints)

        test_results: list[VariantTestResult] = []
        for variant in variants:
            try:
                result = self._test_variant_on_twin(twin, variant, objective)
                test_results.append(result)
            except Exception as exc:
                logger.warning("Variant test failed (%s): %s", variant.tone, exc)
            twin.reset_conversation()

        winner, runner_up = self._select_winner(test_results)

        do_not_send = [
            r for r in test_results if r.risk_score > 0.7 or r.predicted_outcome == "will_respond_negatively"
        ]

        confidence = self._calculate_confidence(test_results, winner)

        warnings: list[str] = []
        if twin.confidence_score < 0.3:
            warnings.append(f"Low profile confidence ({twin.confidence_score:.2f}). " "Predictions may be unreliable.")
        if winner and winner.success_score < 0.4:
            warnings.append(
                "Even the best variant has a low success score. " "Consider revising the objective or timing."
            )
        if len(do_not_send) > len(test_results) / 2:
            warnings.append("Most variants were flagged as risky. " "This recipient may not be receptive right now.")

        duration = time.monotonic() - t0
        logger.info(
            "Optimization complete for %s in %.1fs: %d variants tested",
            self_profile.name,
            duration,
            len(test_results),
        )

        return OptimizationResult(
            user_id=self_profile.user_id,
            user_name=self_profile.name,
            objective=objective,
            original_message=draft_message,
            variants_tested=test_results,
            winner=winner,
            runner_up=runner_up,
            do_not_send=do_not_send,
            confidence=confidence,
            estimated_success_rate=winner.success_score if winner else 0.0,
            warnings=warnings,
        )

    # ------------------------------------------------------------------
    # Public: A/B test
    # ------------------------------------------------------------------

    def ab_test(
        self,
        self_profile: SelfProfile,
        objective: str,
        message_a: str,
        message_b: str,
    ) -> dict[str, Any]:
        """Head-to-head test of two specific messages against the self-twin."""
        twin = DigitalTwin(self_profile)

        variant_a = MessageVariant(
            text=message_a,
            tone="provided",
            approach="provided",
            rationale="User-provided message A",
        )
        result_a = self._test_variant_on_twin(twin, variant_a, objective)
        twin.reset_conversation()

        variant_b = MessageVariant(
            text=message_b,
            tone="provided",
            approach="provided",
            rationale="User-provided message B",
        )
        result_b = self._test_variant_on_twin(twin, variant_b, objective)

        score_a = result_a.success_score * 0.5 + result_a.naturalness_score * 0.3 - result_a.risk_score * 0.2
        score_b = result_b.success_score * 0.5 + result_b.naturalness_score * 0.3 - result_b.risk_score * 0.2

        winner_label = "A" if score_a >= score_b else "B"
        margin = abs(score_a - score_b)

        return {
            "winner": winner_label,
            "confidence": "high" if margin > 0.15 else "medium" if margin > 0.05 else "low",
            "margin": round(margin, 3),
            "message_a": {
                "text": message_a,
                "composite_score": round(score_a, 3),
                "success_score": result_a.success_score,
                "naturalness_score": result_a.naturalness_score,
                "risk_score": result_a.risk_score,
                "predicted_outcome": result_a.predicted_outcome,
                "twin_response": result_a.twin_response,
                "reasoning": result_a.reasoning,
            },
            "message_b": {
                "text": message_b,
                "composite_score": round(score_b, 3),
                "success_score": result_b.success_score,
                "naturalness_score": result_b.naturalness_score,
                "risk_score": result_b.risk_score,
                "predicted_outcome": result_b.predicted_outcome,
                "twin_response": result_b.twin_response,
                "reasoning": result_b.reasoning,
            },
            "recommendation": (
                f"Send message {winner_label}. " + (result_a.reasoning if winner_label == "A" else result_b.reasoning)
            ),
        }

    # ------------------------------------------------------------------
    # Public: batch optimize
    # ------------------------------------------------------------------

    def optimize_batch(
        self,
        items: list[dict[str, Any]],
        num_variants: int = 3,
    ) -> list[OptimizationResult]:
        """
        Optimize messages for multiple users at once.

        Each item must contain:
            - "profile": SelfProfile instance
            - "objective": str
            - "draft": Optional[str]
        """
        results: list[OptimizationResult] = []

        for item in items:
            profile = item.get("profile")
            if not isinstance(profile, SelfProfile):
                logger.warning("Skipping batch item: missing or invalid SelfProfile")
                continue

            objective = item.get("objective", "")
            draft = item.get("draft")

            try:
                result = self.optimize(
                    self_profile=profile,
                    objective=objective,
                    draft_message=draft,
                    num_variants=num_variants,
                )
                results.append(result)
            except Exception as exc:
                logger.error("Batch optimization failed for %s: %s", profile.name, exc)

        return results

    # ------------------------------------------------------------------
    # Public: record outcome for learning
    # ------------------------------------------------------------------

    def record_outcome(
        self,
        user_id: str,
        message_sent: str,
        actual_response: str,
        was_successful: bool,
    ) -> None:
        """Record real outcome for future learning."""
        entry = {
            "user_id": user_id,
            "message_sent": message_sent,
            "actual_response": actual_response,
            "was_successful": was_successful,
            "recorded_at": datetime.now().isoformat(),
        }
        self._history.append(entry)

        logger.info(
            "Recorded outcome for user %s: success=%s (history size: %d)",
            user_id,
            was_successful,
            len(self._history),
        )

    def get_history(self, user_id: str | None = None) -> list[dict[str, Any]]:
        """Retrieve recorded outcomes, optionally filtered by user."""
        if user_id:
            return [h for h in self._history if h["user_id"] == user_id]
        return list(self._history)

    # ------------------------------------------------------------------
    # Internal: variant generation
    # ------------------------------------------------------------------

    def _generate_variants(
        self,
        profile: SelfProfile,
        objective: str,
        draft: str | None,
        num: int,
        constraints: list[str] | None,
    ) -> list[MessageVariant]:
        """Generate message variants using LLM."""
        known_facts: list[str] = []
        if profile.bio:
            known_facts.append(f"Bio: {profile.bio}")
        if profile.self_summary:
            known_facts.append(f"Self-summary: {profile.self_summary}")
        if profile.custom_notes:
            known_facts.append(f"Notes: {profile.custom_notes}")
        if profile.interests:
            known_facts.append(f"Interests: {', '.join(profile.interests)}")

        facts_block = "\n".join(known_facts) if known_facts else "Limited data."

        constraints_block = ""
        if constraints:
            constraints_block = "\nCONSTRAINTS:\n" + "\n".join(f"- {c}" for c in constraints)

        past = [h for h in self._history if h["user_id"] == profile.user_id]
        history_block = ""
        if past:
            successful = [h for h in past if h["was_successful"]]
            failed = [h for h in past if not h["was_successful"]]
            history_parts: list[str] = []
            if successful:
                history_parts.append(
                    "Previously SUCCESSFUL messages: "
                    + "; ".join(f'"{h["message_sent"][:100]}"' for h in successful[-3:])
                )
            if failed:
                history_parts.append(
                    "Previously FAILED messages: " + "; ".join(f'"{h["message_sent"][:100]}"' for h in failed[-3:])
                )
            history_block = "\n\nLEARNING FROM PAST:\n" + "\n".join(history_parts)

        draft_block = ""
        if draft:
            draft_block = f'\nDRAFT MESSAGE TO IMPROVE:\n"{draft}"'

        prompt = f"""Generate {num} different message variants for the user {profile.name} to send.

OBJECTIVE: {objective}

KNOWN ABOUT {profile.name}:
{facts_block}

Language: {profile.language}
{draft_block}{constraints_block}{history_block}

Generate {num} DIVERSE variants. Each must use a different tone and approach.
Suggested diversity:
1. Direct and professional
2. Warm and friendly
3. Indirect / story-based
4. Empathetic and understanding
5. Value-proposition / quid pro quo

Return JSON:
{{
    "variants": [
        {{
            "text": "the message text",
            "tone": "formal|informal|friendly|empathetic|business|urgent|cold",
            "approach": "direct|indirect|storytelling|quid_pro_quo|through_third_party",
            "rationale": "why this variant fits the user's voice"
        }}
    ]
}}

RULES:
- Write in {profile.language} unless the relationship is clearly in another language.
- Make each variant sound natural (real Telegram/WhatsApp message style).
- Keep messages concise.
- Don't be obviously manipulative."""

        messages = [{"role": "user", "content": prompt}]

        try:
            raw = self.llm.chat_json(messages, max_tokens=2000)
            variant_dicts = raw.get("variants", [])
            variants = [
                MessageVariant(
                    text=v.get("text", ""),
                    tone=v.get("tone", "neutral"),
                    approach=v.get("approach", "direct"),
                    rationale=v.get("rationale", ""),
                )
                for v in variant_dicts
                if v.get("text")
            ]
            if not variants:
                raise ValueError("LLM returned no valid variants")
            return variants[:num]
        except Exception as exc:
            logger.warning("Variant generation failed: %s. Using fallback.", exc)
            if draft:
                return [
                    MessageVariant(
                        text=draft,
                        tone="original",
                        approach="as_provided",
                        rationale="Original draft (fallback)",
                    )
                ]
            return [
                MessageVariant(
                    text=f"Buna {profile.name}, {objective}",
                    tone="neutral",
                    approach="direct",
                    rationale="Minimal fallback message",
                )
            ]

    # ------------------------------------------------------------------
    # Internal: test a variant on the twin
    # ------------------------------------------------------------------

    def _test_variant_on_twin(
        self,
        twin: DigitalTwin,
        variant: MessageVariant,
        objective: str,
    ) -> VariantTestResult:
        """Send variant to twin and analyse the response."""
        twin_resp: TwinResponse = twin.chat(variant.text, mode="free_chat")

        analysis = self._analyse_variant_result(
            objective=objective,
            variant=variant,
            twin_response=twin_resp.text,
            user_name=twin.profile.name,
        )

        return VariantTestResult(
            variant=variant,
            twin_response=twin_resp.text,
            success_score=float(analysis.get("success_score", 0.5)),
            naturalness_score=float(analysis.get("naturalness_score", 0.5)),
            risk_score=float(analysis.get("risk_score", 0.3)),
            predicted_outcome=analysis.get("predicted_outcome", "uncertain"),
            reasoning=analysis.get("reasoning", ""),
        )

    def _analyse_variant_result(
        self,
        objective: str,
        variant: MessageVariant,
        twin_response: str,
        user_name: str,
    ) -> dict[str, Any]:
        """Use LLM to score a variant's performance against the twin."""
        prompt = f"""Evaluate this message variant tested on {user_name}'s self-twin.

OBJECTIVE: {objective}

MESSAGE SENT ({variant.tone} / {variant.approach}):
"{variant.text}"

TWIN'S SIMULATED RESPONSE:
"{twin_response}"

Score this interaction and return JSON:
{{
    "success_score": <float 0.0-1.0, likelihood of achieving the objective>,
    "naturalness_score": <float 0.0-1.0, how natural and human the message sounds>,
    "risk_score": <float 0.0-1.0, risk of negative consequences>,
    "predicted_outcome": "<will_respond_positively|will_respond_negatively|will_ignore|will_engage_partially>",
    "reasoning": "<1-2 sentences explaining the scores>"
}}"""

        messages = [{"role": "user", "content": prompt}]

        try:
            raw = self.llm.chat_json(messages, max_tokens=500)
            raw["success_score"] = max(0.0, min(1.0, float(raw.get("success_score", 0.5))))
            raw["naturalness_score"] = max(0.0, min(1.0, float(raw.get("naturalness_score", 0.5))))
            raw["risk_score"] = max(0.0, min(1.0, float(raw.get("risk_score", 0.3))))
            raw.setdefault("predicted_outcome", "uncertain")
            raw.setdefault("reasoning", "")
            return raw
        except Exception as exc:
            logger.warning("Variant analysis failed: %s", exc)
            return {
                "success_score": 0.5,
                "naturalness_score": 0.5,
                "risk_score": 0.3,
                "predicted_outcome": "uncertain",
                "reasoning": f"Analysis failed: {exc}",
            }

    # ------------------------------------------------------------------
    # Internal: winner selection
    # ------------------------------------------------------------------

    def _select_winner(
        self,
        results: list[VariantTestResult],
    ) -> tuple[VariantTestResult | None, VariantTestResult | None]:
        """Select best variant based on composite score."""
        if not results:
            return None, None

        def composite(r: VariantTestResult) -> float:
            return r.success_score * 0.5 + r.naturalness_score * 0.3 - r.risk_score * 0.2

        ranked = sorted(results, key=composite, reverse=True)
        winner = ranked[0]
        runner_up = ranked[1] if len(ranked) > 1 else None
        return winner, runner_up

    def _calculate_confidence(
        self,
        results: list[VariantTestResult],
        winner: VariantTestResult | None,
    ) -> float:
        """Calculate overall confidence in the optimization."""
        if not results or not winner:
            return 0.0

        scores = [r.success_score for r in results]
        avg_score = sum(scores) / len(scores)
        winner_score = winner.success_score

        conf = winner_score * 0.5
        if len(scores) > 1 and avg_score > 0:
            separation = (winner_score - avg_score) / max(avg_score, 0.01)
            conf += min(0.25, separation * 0.15)
        conf -= winner.risk_score * 0.15
        conf += winner.naturalness_score * 0.1

        return round(max(0.0, min(1.0, conf)), 3)
